# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cone_analysis.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1194, 805)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.filter_table = QtWidgets.QTableWidget(Form)
        self.filter_table.setObjectName("filter_table")
        self.filter_table.setColumnCount(0)
        self.filter_table.setRowCount(0)
        self.gridLayout.addWidget(self.filter_table, 2, 0, 1, 6)
        self.load_button = QtWidgets.QPushButton(Form)
        self.load_button.setObjectName("load_button")
        self.gridLayout.addWidget(self.load_button, 0, 5, 1, 1)
        self.subaction_filter_button = QtWidgets.QPushButton(Form)
        self.subaction_filter_button.setObjectName("subaction_filter_button")
        self.gridLayout.addWidget(self.subaction_filter_button, 0, 4, 1, 1)
        self.court_filter_button = QtWidgets.QPushButton(Form)
        self.court_filter_button.setObjectName("court_filter_button")
        self.gridLayout.addWidget(self.court_filter_button, 0, 3, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.rally_button = QtWidgets.QPushButton(Form)
        self.rally_button.setObjectName("rally_button")
        self.gridLayout.addWidget(self.rally_button, 0, 2, 1, 1)
        self.action_filter_button = QtWidgets.QPushButton(Form)
        self.action_filter_button.setObjectName("action_filter_button")
        self.gridLayout.addWidget(self.action_filter_button, 0, 1, 1, 1)
        self.reset_button = QtWidgets.QPushButton(Form)
        self.reset_button.setObjectName("reset_button")
        self.gridLayout.addWidget(self.reset_button, 1, 5, 1, 1)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(760, 210, 67, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(760, 250, 81, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(760, 290, 81, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(760, 330, 81, 17))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.widget, 3, 0, 1, 6)
        self.gridLayout.setRowMinimumHeight(0, 3)
        self.gridLayout.setRowMinimumHeight(1, 1)
        self.gridLayout.setRowMinimumHeight(2, 1)
        self.gridLayout.setColumnStretch(0, 4)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setColumnStretch(3, 1)
        self.gridLayout.setColumnStretch(4, 1)
        self.gridLayout.setColumnStretch(5, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout.setRowStretch(2, 1)
        self.gridLayout.setRowStretch(3, 6)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Zone Analysis"))
        self.load_button.setText(_translate("Form", "Load File"))
        self.subaction_filter_button.setText(_translate("Form", "SubactionFilter"))
        self.court_filter_button.setText(_translate("Form", "CourtFilter"))
        self.rally_button.setText(_translate("Form", "RallyFilter"))
        self.action_filter_button.setText(_translate("Form", "ActionFilter"))
        self.reset_button.setText(_translate("Form", "Reset"))
        self.label.setText(_translate("Form", "< 30%"))
        self.label_2.setText(_translate("Form", "30% - 50%"))
        self.label_3.setText(_translate("Form", "50% - 70%"))
        self.label_4.setText(_translate("Form", "> 70%"))
