# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TVRScouting(object):
    def setupUi(self, TVRScouting):
        TVRScouting.setObjectName("TVRScouting")
        TVRScouting.resize(974, 646)
        icon = QtGui.QIcon.fromTheme("/home/tobiasw/Pictures/varia/gravatar.jpeg")
        TVRScouting.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(TVRScouting)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_7.addWidget(self.lineEdit, 14, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.gridLayout_7.addItem(spacerItem, 7, 1, 1, 1)
        self.matchInfo = QtWidgets.QPushButton(self.centralwidget)
        self.matchInfo.setObjectName("matchInfo")
        self.gridLayout_7.addWidget(self.matchInfo, 6, 1, 1, 2)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_7.addWidget(self.pushButton_3, 4, 1, 1, 2)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_7.addWidget(self.pushButton_2, 11, 1, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_7.addWidget(self.pushButton, 2, 1, 1, 1)
        self.remote_on = QtWidgets.QCheckBox(self.centralwidget)
        self.remote_on.setEnabled(True)
        self.remote_on.setText("")
        self.remote_on.setObjectName("remote_on")
        self.gridLayout_7.addWidget(self.remote_on, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.gridLayout_7.addItem(spacerItem1, 10, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.gridLayout_7.addItem(spacerItem2, 5, 1, 1, 1)
        self.saveFile = QtWidgets.QPushButton(self.centralwidget)
        self.saveFile.setObjectName("saveFile")
        self.gridLayout_7.addWidget(self.saveFile, 9, 1, 1, 2)
        self.loadFile = QtWidgets.QPushButton(self.centralwidget)
        self.loadFile.setObjectName("loadFile")
        self.gridLayout_7.addWidget(self.loadFile, 8, 1, 1, 2)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_7.addWidget(self.textEdit, 1, 0, 12, 1)
        spacerItem3 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.gridLayout_7.addItem(spacerItem3, 3, 1, 1, 1)
        self.remote_stats = QtWidgets.QPushButton(self.centralwidget)
        self.remote_stats.setObjectName("remote_stats")
        self.gridLayout_7.addWidget(self.remote_stats, 1, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.action_view = QtWidgets.QTableWidget(self.centralwidget)
        self.action_view.setAlternatingRowColors(True)
        self.action_view.setObjectName("action_view")
        self.action_view.setColumnCount(0)
        self.action_view.setRowCount(0)
        self.gridLayout_5.addWidget(self.action_view, 0, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_5, 0, 1, 1, 1)
        self.gridLayout_9.setColumnStretch(0, 5)
        self.gridLayout_9.setColumnStretch(1, 1)
        TVRScouting.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TVRScouting)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 974, 22))
        self.menubar.setObjectName("menubar")
        TVRScouting.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TVRScouting)
        self.statusbar.setObjectName("statusbar")
        TVRScouting.setStatusBar(self.statusbar)

        self.retranslateUi(TVRScouting)
        QtCore.QMetaObject.connectSlotsByName(TVRScouting)

    def retranslateUi(self, TVRScouting):
        _translate = QtCore.QCoreApplication.translate
        TVRScouting.setWindowTitle(_translate("TVRScouting", "TVRScouting"))
        self.matchInfo.setText(_translate("TVRScouting", "match info"))
        self.pushButton_3.setText(_translate("TVRScouting", "static analysis"))
        self.pushButton_2.setText(_translate("TVRScouting", "save changes"))
        self.pushButton.setText(_translate("TVRScouting", "same comm"))
        self.saveFile.setText(_translate("TVRScouting", "save file"))
        self.loadFile.setText(_translate("TVRScouting", "load file"))
        self.remote_stats.setText(_translate("TVRScouting", "remote comm"))
